'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Download, FileJson, FileText, Code, File } from 'lucide-react';
import type { AnalysisResult, ReportFormat } from '@/lib/types';
import { toast } from 'sonner';

interface Props {
  data: AnalysisResult;
}

function generateMarkdown(data: AnalysisResult): string {
  const lines: string[] = [
    `# BURNISH Governance Report`,
    ``,
    `**Repository:** ${data.repositoryUrl}`,
    `**Analyzed:** ${new Date(data.analyzedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    `**Provider:** ${data.provider}`,
    ``,
    `---`,
    ``,
    `## Executive Summary`,
    ``,
    data.executiveSummary,
    ``,
    `---`,
    ``,
    `## Governance Score: ${Math.round(data.governanceScore.overall)}/100 (${data.governanceScore.grade})`,
    ``,
    `| Dimension | Score |`,
    `|-----------|-------|`,
    `| Code Quality | ${data.governanceScore.breakdown.codeQuality} |`,
    `| Testing | ${data.governanceScore.breakdown.testing} |`,
    `| Documentation | ${data.governanceScore.breakdown.documentation} |`,
    `| Security | ${data.governanceScore.breakdown.security} |`,
    `| Maintainability | ${data.governanceScore.breakdown.maintainability} |`,
    `| Dependency Mgmt | ${data.governanceScore.breakdown.dependencyManagement} |`,
    ``,
    `---`,
    ``,
    `## Risk Distribution`,
    ``,
    `- **Critical:** ${data.risk.critical} risks`,
    `- **High:** ${data.risk.high} risks`,
    `- **Medium:** ${data.risk.medium} risks`,
    `- **Low:** ${data.risk.low} risks`,
    ``,
    `### Key Risks`,
    ``,
  ];

  data.risk.items.slice(0, 5).forEach((r) => {
    lines.push(`#### [${r.severity.toUpperCase()}] ${r.category}`);
    lines.push(``);
    lines.push(`${r.description}`);
    lines.push(`**Mitigation:** ${r.mitigation}`);
    lines.push(``);
  });

  lines.push(`---`);
  lines.push(``);
  lines.push(`## Repository Health: ${Math.round(data.health.overall)}/100 (${data.health.grade})`);
  lines.push(``);
  lines.push(`| Metric | Score | Status |`);
  lines.push(`|--------|-------|--------|`);
  data.health.metrics.forEach((m) => {
    lines.push(`| ${m.name} | ${m.score}/${m.maxScore} | ${m.status} |`);
  });

  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## Deployment Readiness: ${Math.round(data.deployment.overall)}/100 (${data.deployment.grade})`);
  lines.push(``);
  lines.push(data.deployment.summary);

  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## AI Recommendations`, ``, ``);

  data.recommendations.forEach((r, i) => {
    lines.push(`${i + 1}. **${r.title}** [${r.priority}]`);
    lines.push(`   ${r.description}`);
    lines.push(`   *Category: ${r.category} | Effort: ${r.effort}*`);
    lines.push(``);
  });

  lines.push(`---`);
  lines.push(``);
  lines.push(`*Report generated by BURNISH — AI Repository Governance Platform*`);

  return lines.join('\n');
}

function generateHtml(data: AnalysisResult): string {
  const md = generateMarkdown(data);
  const htmlBody = md
    .split('\n')
    .map((line) => {
      if (line.startsWith('# ')) return `<h1>${line.slice(2)}</h1>`;
      if (line.startsWith('## ')) return `<h2>${line.slice(3)}</h2>`;
      if (line.startsWith('### ')) return `<h3>${line.slice(4)}</h3>`;
      if (line.startsWith('#### ')) return `<h4>${line.slice(5)}</h4>`;
      if (line.startsWith('---')) return '<hr />';
      if (line.startsWith('| ')) return `<p class="table-row">${line}</p>`;
      if (line.startsWith('- **')) return `<li><strong>${line.slice(4)}</li>`;
      if (line.startsWith('**') && line.endsWith('**')) return `<p><strong>${line.slice(2, -2)}</strong></p>`;
      if (line.trim() === '') return '';
      return `<p>${line}</p>`;
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BURNISH Report - ${data.repositoryMeta.owner}/${data.repositoryMeta.name}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #e5e7eb; background: #111827; line-height: 1.6; }
    h1 { font-size: 2rem; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; margin-bottom: 24px; }
    h2 { font-size: 1.5rem; color: #93c5fd; margin-top: 32px; } h3 { font-size: 1.2rem; color: #d1d5db; margin-top: 24px; }
    hr { border: none; border-top: 1px solid #374151; margin: 32px 0; }
    li { margin: 8px 0; }
    .table-row { font-family: monospace; font-size: 14px; }
    strong { color: #f3f4f6; }
  </style>
</head>
<body>
${htmlBody}
</body>
</html>`;
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function ReportExport({ data }: Props) {
  const [isExporting, setIsExporting] = useState(false);

  const repoSlug = `${data.repositoryMeta.owner}-${data.repositoryMeta.name}`;

  const handleExport = async (format: ReportFormat) => {
    setIsExporting(true);
    try {
      switch (format) {
        case 'json': {
          downloadFile(JSON.stringify(data, null, 2), `burnish-${repoSlug}.json`, 'application/json');
          break;
        }
        case 'markdown': {
          const md = generateMarkdown(data);
          downloadFile(md, `burnish-${repoSlug}.md`, 'text/markdown');
          break;
        }
        case 'html': {
          const html = generateHtml(data);
          downloadFile(html, `burnish-${repoSlug}.html`, 'text/html');
          break;
        }
        case 'pdf': {
          const html = generateHtml(data);
          const printWindow = window.open('', '_blank');
          if (printWindow) {
            printWindow.document.write(html);
            printWindow.document.close();
            setTimeout(() => { printWindow.print(); }, 500);
          }
          break;
        }
      }
      toast.success(`Report exported as ${format.toUpperCase()}`);
    } catch {
      toast.error('Export failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Card className="bg-card/80 border-border/50">
      <CardHeader className="pb-3">
        <CardTitle className="text-base font-semibold flex items-center gap-2">
          <Download className="h-4 w-4 text-primary" />
          Export Report
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex flex-wrap gap-2">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm" disabled={isExporting} className="border-border/50">
                <Download className="h-3.5 w-3.5 mr-1.5" />
                Export As
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start">
              <DropdownMenuItem onClick={() => handleExport('json')}>
                <FileJson className="h-4 w-4 mr-2" /> JSON
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport('markdown')}>
                <FileText className="h-4 w-4 mr-2" /> Markdown
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport('html')}>
                <Code className="h-4 w-4 mr-2" /> HTML
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport('pdf')}>
                <File className="h-4 w-4 mr-2" /> PDF (Print)
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
        <p className="text-xs text-muted-foreground mt-3">
          Export the full governance report in your preferred format. PDF uses browser print dialog.
        </p>
      </CardContent>
    </Card>
  );
}
